# Optimise la RAM globale en activant le mode smol de Bun
smol = true

[install]
# Hoist deps autant que possible (vitesse + déduplication)
hoist = true
saveTextLockfile = true
exact = false
registry = "https://registry.npmjs.org/"

[install.scopes]
"@rpbey" = { url = "https://registry.npmjs.org/" }

[run]
# Permet d'utiliser bun comme task runner sans préfixe
bun = true
silent = false

[test]
coverage = false
