/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Hash FNV-1a 32-bit sur les bytes UTF-8 de l'input, renvoie l'hex.
 * Utilisé pour générer les ETag des routes `/api/public/*`.
 */
export declare function fnv1AHex(input: string): string

/** Format d'une durée en ms vers `"3j"`, `"4h"`, `"15min"`, `"42s"`. */
export declare function formatDuration(ms: number): string

/** Renvoie le niveau atteint pour un XP donné. 0 si en-dessous du palier 1. */
export declare function levelForXp(xp: number): number

export declare function nextThresholdFrom(xp: number): XpProgress | null

/**
 * Parse `"10m"`, `"1h"`, `"7d"`, `"2w"` → millisecondes. None si format invalide.
 * Compatible avec `parseDuration(input)` de `lib/sanction-helpers.ts`.
 */
export declare function parseDurationMs(s: string): number | null

/** Progression vers le prochain palier. `None` si déjà au niveau max. */
export interface XpProgress {
  current: number
  nextLevel: number
  nextLevelXp: number
  needed: number
}
